###

POST http://localhost:5000/api/user/login
Content-Type: application/json

{"email":"huynhmytram2602@gmail.com","password":"123123123"}

###
POST http://localhost:5000/api/user
Content-Type: application/json

{
  "uuid": "e4a4975d-6c0c-4555-aea3-984ec300c713",
  "displayName": "Phan Thanh THanhhhhhhh"
}

###

PUT http://localhost:5000/api/user?uuid=e4a4975d-6c0c-4555-aea3-984ec300c713
Content-Type: application/json

{
  "displayName": "Nguyen Truong Minh Thuan"
}

###

DELETE http://localhost:5000/api/user?uuid=asdasd

###

GET http://localhost:5000/api/contact?uuid=6bf9b392-3c5c-4936-b97e-21a1cf92337a

###

POST http://localhost:5000/api/contact?uuid=fba9374f-7f79-4887-b5d0-2adbaa273b50

###

PUT http://localhost:5000/api/contact/addcontact?uuid=6bf9b392-3c5c-4936-b97e-21a1cf92337a
Content-Type: application/json

{
  "uuid": "123123123123123",
  "nickname": "Con cac"
}

###

GET http://localhost:5000/auth

###

GET http://localhost:5000/api/conversation?uuid=6bf9b392-3c5c-4936-b97e-21a1cf92337a
Content-Type: application/json

###
POST http://localhost:5000/api/conversation/startConversation?uuid=6bf9b392-3c5c-4936-b97e-21a1cf92337a
Content-Type: application/json

[
  "e926bddc-5fbe-4e7b-afc5-0fa1900d0f57"
]

###
GET http://localhost:5000/api/message?conversationId=6040cb58c0be53f4fa6e4977&uuid=6bf9b392-3c5c-4936-b97e-21a1cf92337a

###
PUT http://localhost:5000/api/message/sendMessage?conversationId=6040cb58c0be53f4fa6e4977&uuid=6bf9b392-3c5c-4936-b97e-21a1cf92337a
Content-Type: application/json

{
  "uuid" :"6bf9b392-3c5c-4936-b97e-21a1cf92337a",
  "content": "New message"
}

###
PUT http://localhost:5000/api/message/limit
